name: Update Config and Run

on:
  workflow_dispatch:
    inputs:
      pull_number:
        description: 'Pull Request Number'
        required: false
      root_directory:
        description: 'Root Directory'
        required: true
        default: './packages/core/src'
      excluded_directories:
        description: 'Excluded Directories (comma-separated)'
        required: true
        default: 'node_modules'
      reviewers:
        description: 'Pull Request Reviewers (comma-separated)'
        required: true

jobs:
  update-and-run:
    runs-on: ubuntu-latest

    env:
      GITHUB_ACCESS_TOKEN: ${{ secrets.GH_PAT }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23.3.0'  # Updated to match required version

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false  # We'll run install separately with specific flags

      # Clean install without frozen lockfile to update dependencies
      - name: Install dependencies
        run: |
          pnpm install --no-frozen-lockfile
          pnpm up  # Update all dependencies to their latest allowed versions

      - name: Update config file
        run: |
          # Convert comma-separated excluded directories to JSON array
            EXCLUDED_DIRS_JSON=$(echo "${{ github.event.inputs.excluded_directories }}" | \
              jq -R 'split(",") | map(sub("^\\s+|\\s+$"; ""))')

          # Convert comma-separated reviewers to JSON array
          REVIEWERS_JSON=$(echo "${{ github.event.inputs.reviewers }}" | \
            jq -R 'split(",") | map(sub("^\\s+|\\s+$"; ""))')

          # Update config.json using jq
          jq --arg pn "${{ github.event.inputs.pull_number }}" \
             --arg rd "${{ github.event.inputs.root_directory }}" \
             --argjson ed "${EXCLUDED_DIRS_JSON}" \
             --argjson pr "${REVIEWERS_JSON}" \
             '.repository.pullNumber = if $pn == "" then null else ($pn | tonumber) end |
              .rootDirectory = $rd |
              .excludedDirectories = $ed |
              .pullRequestReviewers = $pr' \
             packages/jsdoc-automation/src/config/config.json > temp.json && mv temp.json packages/jsdoc-automation/src/config/config.json

      - name: Run start command
        run: cd packages/jsdoc-automation && pnpm start  # Added cd to correct directory
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GH_PAT }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}